don't use RPI_RUN_ONCE and RPI_RUN_PHASE anymore

diff --git a/bootstrap-plugins/apt b/bootstrap-plugins/apt
--- a/bootstrap-plugins/apt
+++ b/bootstrap-plugins/apt
@@ -9,14 +9,38 @@
 
 # default options
 RPI_APT_INTERACTIVE="${RPI_APT_INTERACTIVE:=false}"
+RPI_APT_ON="${RPI_APT_ON:=login}"
 to_array RPI_APT_CMDS
 
 # load dependencies
 plugin_load run || return 1
 
 
+function run() {
+    case "${RPI_APT_ON}" in
+        "login")
+            rpi_run_on_first_login "$@"
+            ;;
+
+        "boot")
+            rpi_run_on_first_boot "$@"
+            ;;
+
+        ?|*)
+            error "invalid RPI_APT_ON=${RPI_APT_ON}"
+    esac
+}
+
 rpi_apt_prerun() {
     [[ -n "${RPI_APT_CMDS}" ]] || return 1
+    case "${RPI_APT_ON}" in
+        "login")
+            ;;
+        "boot")
+            ;;
+        ?|*)
+            error "invalid RPI_APT_ON=${RPI_APT_ON} - valid: login, boot"
+    esac
     return 0
 }
 
@@ -25,10 +49,10 @@ rpi_apt_run() {
     for cmd in "${RPI_APT_CMDS[@]}" ; do
         # run in interactive mode?
         if [[ "${RPI_APT_INTERACTIVE}" == "true" ]] ; then
-            RPI_RUN_ONCE=true rpi_run "sudo apt ${cmd}" || error "apt"
+            run "sudo apt ${cmd}" || error "apt"
         # run in non-interactive mode
         else
-            RPI_RUN_ONCE=true rpi_run "sudo DEBIAN_FRONTEND=noninteractive apt --yes --quiet ${cmd}" || error "install apt update"
+            run "sudo DEBIAN_FRONTEND=noninteractive apt --yes --quiet ${cmd}" || error "install apt update"
         fi
     done
 }
@@ -40,4 +64,5 @@ function rpi_apt_description() {
 function rpi_apt_help_params() {
     help_param "RPI_APT_CMDS" "array of apt commands to execute"
     help_param "RPI_APT_INTERACTIVE" "run in interactive mode"
+    help_param "RPI_APT_ON" "login=run on login, boot=run on boot"
 }
diff --git a/bootstrap-plugins/dist b/bootstrap-plugins/dist
--- a/bootstrap-plugins/dist
+++ b/bootstrap-plugins/dist
@@ -11,6 +11,7 @@
 # RPI_DIST_COPY=( "/etc", "/home", "/usr" )
 
 # default options
+RPI_DIST_ON="${RPI_DIST_ON:=bake}"
 to_array RPI_DIST_COPY
 to_array RPI_DIST_APPEND
 
@@ -20,6 +21,25 @@ plugin_load run || return 1
 plugin_load chmod || return 1
 plugin_load chown || return 1
 
+
+function run() {
+    case "${RPI_DIST_ON}" in
+        "bake")
+            rpi_run_on_bake "$@"
+            ;;
+
+        "login")
+            rpi_run_on_first_login "$@"
+            ;;
+
+        "boot")
+            rpi_run_on_first_boot "$@"
+            ;;
+
+        ?|*)
+            error "invalid RPI_DIST_ON=${RPI_DIST_ON}"
+    esac
+}
 
 function rpi_dist_prerun() {
     true
@@ -50,6 +70,7 @@ function rpi_dist_help_params() {
     help_param "RPI_DIST_COPY" "array of files to copy to disk image"
     help_param "RPI_DIST_COPY_BOOT" "array of files to copy when the pi is booting"
     help_param "RPI_DIST_APPEND" "array of files to append to files on disk image"
+    help_param "RPI_DIST_ON" "copy on \"bake\", first \"boot\" or first \"login\""
 }
 
 # ---------------------------------------------------------------------
@@ -115,15 +136,15 @@ function rpi_dist_cp_after_boot() {
         # copy to image
         sudo cp -r "${RPI_USER_DISTDIR}/${path}"/* "${distdir}/$(dirname "${path}")" || sudo cp -r "${RPI_DISTDIR}/${path}"/* "${distdir}/$(dirname "${path}")" || error "cp"
         # register copy command
-        RPI_RUN_ONCE=true rpi_run "sudo cp -r \"/home/pi/bootstrap-dist/${path}/\"* \"/$(dirname "${path}")" || error "rpi_run"
+        run "sudo cp -r \"/home/pi/bootstrap-dist/${path}/\"* \"/$(dirname "${path}")" || error "rpi_run"
     # copy file?
     else
         sudo cp -r "${RPI_USER_DISTDIR}/${path}" "${distdir}/$(dirname "${path}")/" || sudo cp -r "${RPI_DISTDIR}/${path}" "${distdir}/$(dirname "${path}")/" || error "cp"
-        RPI_RUN_ONCE=true rpi_run "sudo cp \"/home/pi/bootstrap-dist/${path}\" \"/$(dirname "${path}")/\"" || error "rpi_run"
+        run "sudo cp \"/home/pi/bootstrap-dist/${path}\" \"/$(dirname "${path}")/\"" || error "rpi_run"
     fi
     # chmod?
-    [[ -n "${permissions}" ]] && { RPI_RUN_ONCE=true rpi_run "sudo chmod -R \"${permissions}\" \"${path}\"" || error "chmod" ; }
+    [[ -n "${permissions}" ]] && { run "sudo chmod -R \"${permissions}\" \"${path}\"" || error "chmod" ; }
     # chown
-    RPI_RUN_ONCE=true rpi_run "sudo chown -R pi:pi \"${path}\"" || error "chown"
+    run "sudo chown -R pi:pi \"${path}\"" || error "chown"
 
 }
diff --git a/bootstrap-plugins/systemctl b/bootstrap-plugins/systemctl
--- a/bootstrap-plugins/systemctl
+++ b/bootstrap-plugins/systemctl
@@ -8,11 +8,27 @@
 
 
 # default options
+RPI_SYSTEMCTL_ON="${RPI_SYSTEMCTL_ON:=login}"
 to_array RPI_SYSTEMCTL_CMDS
 
 # load dependencies
 plugin_load run || return 1
 
+
+function run() {
+    case "${RPI_SYSTEMCTL_ON}" in
+        "login")
+            rpi_run_on_first_login "$@"
+            ;;
+
+        "boot")
+            rpi_run_on_first_boot "$@"
+            ;;
+
+        ?|*)
+            error "invalid RPI_SYSTEMCTL_ON=${RPI_SYSTEMCTL_ON}"
+    esac
+}
 
 function rpi_systemctl_prerun() {
     [[ -n "${RPI_SYSTEMCTL_CMDS}" ]] || { warn "RPI_SYSTEMCTL_CMDS must be set" ; return 1 ; }
@@ -21,7 +37,7 @@ function rpi_systemctl_prerun() {
 
 function rpi_systemctl_run() {
     for cmd in "${RPI_SYSTEMCTL_CMDS[@]}" ; do
-        RPI_RUN_ONCE=true rpi_run "sudo systemctl ${cmd}" || error "install systemctl ${cmd}"
+        run "sudo systemctl ${cmd}" || error "install systemctl ${cmd}"
     done
 }
 
@@ -31,4 +47,5 @@ function rpi_systemctl_description() {
 
 function rpi_systemctl_help_params() {
     help_param "RPI_SYSTEMCTL_CMDS" "array of systemctl commands"
+    help_param "RPI_SYSTEMCTL_ON" "run on first \"boot\" or first \"login\""
 }
