outsource loopback_*(), mount_*() -> loopback plugin

diff --git a/bootstrap-plugins/raspbian b/bootstrap-plugins/raspbian
--- a/bootstrap-plugins/raspbian
+++ b/bootstrap-plugins/raspbian
@@ -12,6 +12,7 @@ function rpi_raspbian_prerun() {
     [[ -n "${RPI_DOWNLOAD_RASPBIAN_URL:=}" ]] || error "RPI_DOWNLOAD_RASPBIAN_URL check"
     # load dependencies
     plugin_load "download" || return 1
+    plugin_load "loopback" || return 1
 }
 
 function rpi_raspbian_run() {
@@ -39,14 +40,28 @@ function rpi_raspbian_run() {
 
     # mount image
     echo " setting up loopback for ${dest}"
-    loopback_setup "${dest}" || error "loopback setup"
-    mount_image || error "image mount"
+    RPI_LOOPBACK_IMAGE="${dest}"
+    plugin_run loopback || return 1
+    # read os-release
+    . "${RPI_ROOT}/etc/os-release"
+
+    return 0
 }
 
 function rpi_raspbian_postrun() {
     echo " cleaning up..."
-    umount_image
-    loopback_cleanup
+    # cleanup os-release
+    unset PRETTY_NAME
+    unset NAME
+    unset VERSION_ID
+    unset VERSION
+    unset ID
+    unset ID_LIKE
+    unset HOME_URL
+    unset SUPPORT_URL
+    unset BUG_REPORT_URL
+    # tear down loopback device & unmount partitions
+    plugin_postrun loopback
 }
 
 function rpi_raspbian_description() {
