rename RUN_MODE -> RUN_PHASE; add RUN_PHASE=bake; cleanup

diff --git a/bootstrap-plugins/run b/bootstrap-plugins/run
--- a/bootstrap-plugins/run
+++ b/bootstrap-plugins/run
@@ -13,7 +13,8 @@
 
 
 # default options
-RPI_RUN_MODE="${RPI_RUN_MODE:=login}"
+RPI_RUN_PHASE="${RPI_RUN_PHASE:=login}"
+
 to_array RPI_RUN
 to_array RPI_RUN_ONCE
 
@@ -24,30 +25,25 @@ plugin_load chown || return 1
 
 
 function rpi_run_prerun() {
-    { [[ -n "${RPI_RUN_ONCE}" ]] || [[ -n "${RPI_RUN}" ]] ; } || error "RPI_RUN_ONCE and RPI_RUN unset."
-    case "${RPI_RUN_MODE}" in
+    [[ -n "${RPI_RUN_PHASE}" ]] || error "RPI_RUN_PHASE unset."
+    [[ -n "${RPI_RUN}" ]] || error "RPI_RUN unset."
+    case "${RPI_RUN_PHASE}" in
+        "bake")
+            ;;
+
         "login")
             ;;
 
         "boot")
             ;;
 
-        "script")
-            ;;
-
         ?|*)
-            error "invalid RPI_RUN_MODE. Use one of login, boot, script. rpi_run_once"
+            error "invalid RPI_RUN_PHASE. Use one of bake, boot, login"
     esac
 }
 
 function rpi_run_run() {
-    if [[ -n "${RPI_RUN_ONCE}" ]] ; then
-        rpi_run_once "${RPI_RUN_ONCE[@]}"
-    fi
-
-    if [[ -n "${RPI_RUN}" ]] ; then
         rpi_run "${RPI_RUN[@]}"
-    fi
 }
 
 function rpi_run_description() {
@@ -55,9 +51,9 @@ function rpi_run_description() {
 }
 
 function rpi_run_help_params() {
-    help_param "RPI_RUN_ONCE" "command to run once (on setup)"
-    help_param "RPI_RUN" "command to run regularly (on every boot/login/script call)"
-    help_param "RPI_RUN_MODE" "decides how to run the command: login (from .bashrc when pi user logs in), boot (rc.local when pi boots), script (external script)"
+    help_param "RPI_RUN" "command or path to script to run"
+    help_param "RPI_RUN_PHASE" "boot (run on boot), login (run on login), bake (run on host during image generation)"
+    help_param "RPI_RUN_ONCE" "only run once if set"
 }
 
 # ---------------------------------------------------------------------
@@ -124,63 +120,39 @@ function rpi_run_on_first_boot() {
     done
 }
 
-# output command to script
-function rpi_run_script() {
-    local scriptname="${RPI_WORKDIR}/rpi_run.sh"
-    for cmd in "$@" ; do
-        rpi_append_to_file "${cmd}" "${scriptname}" || error "append ${cmd} to ${_}"
-        log "(rpi_run.sh) cmd installed: \"${cmd}\""
-    done
-}
-
 # output command to once-script
-function rpi_run_once_script() {
-    local scriptname="${RPI_WORKDIR}/rpi_run_once.sh"
+function rpi_run_on_bake() {
     for cmd in "$@" ; do
-        rpi_append_to_file "${cmd}" "${scriptname}" || error "append ${cmd} to ${_}"
-        log "(rpi_run_once.sh) cmd installed: \"${cmd}\""
+        log "running: \"${cmd}\""
+        "${cmd}" || error "${cmd}"
     done
 }
-
-# run command once (either on first boot or on first login)
-function rpi_run_once() {
-    [[ -n "$*" ]] || error "missing argument"
-    case "${RPI_RUN_MODE}" in
-        "login")
-            rpi_run_on_first_login "$@"
-            ;;
-
-        "boot")
-            rpi_run_on_first_boot "$@"
-            ;;
-
-        "script")
-            rpi_run_once_script "$@"
-            ;;
-
-        ?|*)
-            error "invalid RPI_RUN_MODE. Use one of login, boot, script. rpi_run_once"
-    esac
-}
-
 
 # run command (either on boot or on login)
 function rpi_run() {
     [[ -n "$*" ]] || error "missing argument"
-    case "${RPI_RUN_MODE}" in
+    case "${RPI_RUN_PHASE}" in
+        "bake")
+            rpi_run_on_bake "$@"
+            ;;
+
         "login")
-            rpi_run_on_login "$@"
+            if [[ -n "${RPI_RUN_ONCE}" ]] ; then
+                rpi_run_on_first_login "$@"
+            else
+                rpi_run_on_login "$@"
+            fi
             ;;
 
         "boot")
-            rpi_run_on_boot "$@"
-            ;;
-
-        "script")
-            rpi_run_script "$@"
+            if [[ -n "${RPI_RUN_ONCE}" ]] ; then
+                rpi_run_on_first_boot "$@"
+            else
+                rpi_run_on_boot "$@"
+            fi
             ;;
 
         ?|*)
-            error "invalid RPI_RUN_MODE. Use one of login, boot, script. rpi_run"
+            error "invalid RPI_RUN_PHASE."
     esac
 }
