implement RPI_RUN; properly handle command arrays

diff --git a/bootstrap-plugins/run b/bootstrap-plugins/run
--- a/bootstrap-plugins/run
+++ b/bootstrap-plugins/run
@@ -15,6 +15,7 @@
 # default options
 RPI_RUN_ONCE="${RPI_RUN_ONCE:=}"
 RPI_RUN_ON_BOOT="${RPI_RUN_ON_BOOT:=false}"
+RPI_RUN="${RPI_RUN:=}"
 
 # load dependencies
 plugin_load append || return 1
@@ -23,12 +24,16 @@ plugin_load chown || return 1
 
 
 function rpi_run_prerun() {
-    [[ -n "${RPI_RUN_ONCE}" ]] || error "RPI_RUN_ONCE unset."
+    { [[ -n "${RPI_RUN_ONCE}" ]] || [[ -n "${RPI_RUN}" ]] ; } || error "RPI_RUN_ONCE and RPI_RUN unset."
 }
 
 function rpi_run_run() {
     if [[ -n "${RPI_RUN_ONCE}" ]] ; then
         rpi_run_once "${RPI_RUN_ONCE[@]}"
+    fi
+
+    if [[ -n "${RPI_RUN}" ]] ; then
+        rpi_run "${RPI_RUN[@]}"
     fi
 }
 
@@ -38,14 +43,17 @@ function rpi_run_description() {
 
 function rpi_run_help_vars() {
     help_var "RPI_RUN_ONCE" "command to run once (on setup)"
+    help_var "RPI_RUN" "command to run on every boot/login"
     help_var "RPI_RUN_ON_BOOT" "if true, run command on boot from rc.local otherwise run on login from .bashrc"
 }
 
 # ---------------------------------------------------------------------
 # run command on login
 function rpi_run_on_login() {
-    local cmd="$1"
-    rpi_append_to_file "${cmd}" "${RPI_ROOT}/home/pi/.bashrc" || error "rpi_append_to_file"
+    for cmd in "$@" ; do
+        rpi_append_to_file "${cmd}" "${RPI_ROOT}/home/pi/.bashrc" || error "rpi_append_to_file"
+        log "(login) cmd installed: \"${cmd}\""
+    done
 }
 
 # run command once upon first login
@@ -61,20 +69,24 @@ function rpi_run_on_first_login() {
         sudo chmod +x "${RPI_ROOT}/${once_script}" || error "sudo chmod +x"
         sudo chown root:root "${RPI_ROOT}/${once_script}" || error "chown"
     fi
-    # append to script
-    rpi_append_to_file "echo -e '--------------------------------------\nexecuting: $*\n--------------------------------------'" "${RPI_ROOT}/${once_script}"
-    rpi_append_to_file "$* || exit 1"         "${RPI_ROOT}/${once_script}"
-    rpi_chown_pi "${once_script}" || error "chown"
-    log "(login) cmd installed: \"$*\""
+    for cmd in "$@" ; do
+        # append to script
+        rpi_append_to_file "echo -e '--------------------------------------\nexecuting: ${cmd}\n--------------------------------------'" "${RPI_ROOT}/${once_script}"
+        rpi_append_to_file "${cmd} || exit 1"         "${RPI_ROOT}/${once_script}"
+        rpi_chown_pi "${once_script}" || error "chown"
+        log "(first login) cmd installed: \"${cmd}\""
+    done
 }
 
 # run on every boot
 function rpi_run_on_boot() {
-    local cmd="$1"
     # remove "exit 0" at the end if it's there, so we
     # can simply append commands
     rpi_remove_pattern_from_file "exit 0" "${RPI_ROOT}/etc/rc.local" || error "remove exit from rc.local"
-    rpi_append_to_file "${cmd}" "${RPI_ROOT}/etc/rc.local" || error "append ${cmd} to rc.local"
+    for cmd in "$@" ; do
+        rpi_append_to_file "${cmd}" "${RPI_ROOT}/etc/rc.local" || error "append ${cmd} to rc.local"
+        log "(boot) cmd installed: \"${cmd}\""
+    done
 }
 
 # run command once upon first boot
@@ -90,19 +102,32 @@ function rpi_run_on_first_boot() {
         sudo chmod +x "${RPI_ROOT}/${once_script}" || error "sudo chmod +x"
         sudo chown root:root "${RPI_ROOT}/${once_script}" || error "chown"
     fi
-    # append to script
-    rpi_append_to_file "echo -e '--------------------------------------\nexecuting: $*\n--------------------------------------'" "${RPI_ROOT}/${once_script}"
-    rpi_append_to_file "$* || exit 1"         "${RPI_ROOT}/${once_script}"
-    rpi_chown_pi "${once_script}" || error "chown"
-    log "(boot) cmd installed: \"$*\""
+    for cmd in "$@" ; do
+        # append to script
+        rpi_append_to_file "echo -e '--------------------------------------\nexecuting: ${cmd}\n--------------------------------------'" "${RPI_ROOT}/${once_script}"
+        rpi_append_to_file "${cmd} || exit 1"         "${RPI_ROOT}/${once_script}"
+        rpi_chown_pi "${once_script}" || error "chown"
+        log "(first boot) cmd installed: \"${cmd}\""
+    done
 }
 
 # run command once (either on first boot or on first login)
 function rpi_run_once() {
     [[ -n "$*" ]] || error "missing argument"
     if [[ "${RPI_RUN_ON_BOOT}" == "true" ]] ; then
-        rpi_run_on_first_boot "$*"
+        rpi_run_on_first_boot "$@"
     else
-        rpi_run_on_first_login "$*"
+        rpi_run_on_first_login "$@"
+    fi
+}
+
+
+# run command (either on boot or on login)
+function rpi_run() {
+    [[ -n "$*" ]] || error "missing argument"
+    if [[ "${RPI_RUN_ON_BOOT}" == "true" ]] ; then
+        rpi_run_on_boot "$@"
+    else
+        rpi_run_on_login "$@"
     fi
 }
